[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch", "googleapis"]
  included_files = [
    "netlify/functions/keys/google-service-account.json",
    "netlify/functions/**/*.cjs"
  ]
  node_bundler = "esbuild"

[build]
  publish = "dist"
  command = "npm run build"

[functions.uploadDirectToDrive]
  included_files = ["*"]
  external_node_modules = ["googleapis"]
  node_bundler = "esbuild"
  format = "cjs"

[dev]
  envFiles = [".env"]

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_STRIPE_PUBLISHABLE_KEY"


