# Netlify configuration for ColumbiaPA300 civic platform

[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch", "googleapis"]
  node_bundler = "esbuild"

[build]
  publish = "dist"
  command = "npm run build"

# Function-specific overrides
[functions.uploadDirectToDrive]
  external_node_modules = ["googleapis"]
  node_bundler = "esbuild"
  format = "cjs"

[dev]
  envFiles = [".env"]

[build.environment]
  # Ensure no secrets are exposed in builds
  SECRETS_SCAN_OMIT_KEYS = "VITE_STRIPE_PUBLISHABLE_KEY"
